injector:
  # True if you want to enable vault agent injection.
  # @default: global.enabled
  enabled: true

  replicas: 2

server:
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: "internal-ingress"
    activeService: false

  ha:
    enabled: true
    replicas: 1
    raft:
      enabled: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "file" {
          path = "/vault/data"
        }

        seal "awskms" { 
          region = "ap-south-1" 
          kms_key_id = "65873138-2848-4c82-852e-fd7c7386cf84"
        }

  serviceAccount:
    create: true
    name: "vault"
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::218306567362:role/smruti-VaultEKSRole"
