apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: vault
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'internal-app'
    vault.hashicorp.com/agent-inject-secret-config.txt: 'kv/dev/apps/service01'
spec:
  containers:
  - image: nginx:latest
    name: nginx
  serviceAccountName: internal-app