apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-agent-injector-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-agent-injector-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: vault-agent-injector
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-agent-injector-role
