{{- if .Values.Deployment.enabled}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Values.Deployment.labels.app }}
spec:
  replicas: {{ .Values.Deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.Deployment.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.Deployment.labels.app }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.Deployment.containers.image }}{{ if .Values.Deployment.containers.tag }}:{{ .Values.Deployment.containers.tag }}{{ end }}
          args:
          {{- if .Values.Deployment.args }}
          {{- range .Values.Deployment.args }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}
          ports:
          {{- if .Values.Deployment.containers.ports }}
          {{- range .Values.Deployment.containers.ports }}
            - containerPort: {{ .containerPort }}
          {{- end }}
          {{- end }}
          # Conditionally add environment variables
          env:
          {{- if .Values.Deployment.env }}
          {{- range .Values.Deployment.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- end }}

          {{- if .Values.Deployment.resources }}
          resources:
          {{- if .Values.Deployment.resources.requests }}
          requests:
            {{- if .Values.Deployment.resources.requests.cpu }}
            cpu: {{ .Values.Deployment.requests.cpu | quote }}
            {{- end }}
            {{- if .Values.Deployment.resources.requests.memory }}
            memory: {{ .Values.Deployment.resources.requests.memory | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.Deployment.resources.limits }}
          limits:
            {{- if .Values.Deployment.resources.limits.cpu }}
            cpu: {{ .Values.Deployment.resources.limits.cpu | quote }}
            {{- end }}
            {{- if .Values.Deployment.resources.limits.memory }}
            memory: {{ .Values.Deployment.resources.limits.memory | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
          # Conditionally add volume mounts
          volumeMounts:
          {{- if .Values.Deployment.volumeMounts }}
          {{- range .Values.Deployment.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath | quote }}
              {{- if .subPath}}
              subPath: {{ .subPath}}
              {{- end }}
              {{- if .readOnly }}
              readOnly: {{ .readOnly }}
              {{- end }}
          {{- end }}
          {{- end }}
      # Conditionally add volumes
      volumes:
      {{- if .Values.Deployment.volumes }}
      {{- range .Values.Deployment.volumes }}
        - name: {{ .name }}
          {{- if .configMap }}
          configMap:
            name: {{ .configMap.name }}
          {{- end }}
      {{- end }}
      {{- end }}

{{- end }}