apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Values.Service.labels.app }}
spec:
  selector:
    app: {{ .Values.Service.labels.app }}
  {{- if .Values.Service.clusterIP }}
  clusterIP: {{ .Values.Service.clusterIP }}
  {{- end }}
  ports:
  {{- if .Values.Service.ports }}
  {{- range .Values.Service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
  {{- end }}
  type: {{ .Values.Service.type }}
